---
title: "Vignette Title"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
library(tidyverse)
library(hathidy)
fitz = read_csv("~/Dropbox/lib/hathi/fitz.csv", col_names = "htid")
munro = read_csv("~/Dropbox/hathi_metadata/Munro.csv", col_names = "htid") %>% pull(htid) 
#options(hathidy_dir = "/drobo/feature-counts")
```

```{r}
#options(hathidy_dir = "/drobo/feature-counts")
data = hathi_counts(fitz$htid, metadata = c("title"))

data %>% filter(str_detect(title, "Gatsby")) %>% ungroup %>% sample_n(13)
```


```{r}

totals = munro %>% group_by(htid, page, token ) %>% summarize(count = sum(count)) 
bookcounts = munro %>% group_by(htid, token) %>% summarize(count=sum(count))

normalize_counts = . %>% mutate(norm = count/sqrt(sum(count^2))) 

cosine_similarity = function(book1, book2) {
  # Assumes that they are frames that have a 'norm' column.
  book1 %>% inner_join(book2, by='token') %>% mutate(p = norm.x*norm.y) %>% pull(p) %>% sum
}

normed_books = bookcounts %>% group_by(htid) %>%
  normalize_counts

interactions = normed_books %>% pull(htid) %>% unique %>% combn(2, simplify = F) %>% map(~ {
  x = .[1]
  y = .[2]
  z = cosine_similarity(normed_books %>% filter(htid==x), normed_books %>% filter(htid==y))
  data_frame(a = x, b = y, similarity = z)
}) %>% bind_rows

interactions %>% ggplot() + geom_tile(aes(x = a, y = b, fill= 1 - dist))

```


```{r}

chunked = munro %>% add_chunks(count, length=2000) %>% group_by(htid, token, chunk) %>% summarize(count=sum(count))
chunked
normed = chunked %>% group_by(htid, chunk) %>% normalize_counts

groups = normed %>% ungroup %>% split(interaction(normed$chunk, normed$htid)) 


interactions = data_frame(x = 1:(35*10)) %>% expand(y = 1:(35*10), x) %>% filter(x < y)

all_of_them = interactions %>% rowwise %>% mutate(dist = cosine_similarity(groups[[x]], groups[[y]]))

all_of_them %>% ggplot() + geom_tile() + aes(x=x, y = -y, fill = dist) + scale_fill_viridis_c()

```

